
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Main.module.css'
import Menu from '../../components/Menu'
import Footer from '../../components/Footer'
import Gallery from '../../components/Gallery'
import { Col, Container, Row } from 'react-bootstrap'

import lightGallery from 'lightgallery';
// Plugins
import lgThumbnail from 'lightgallery/plugins/thumbnail'
import lgZoom from 'lightgallery/plugins/zoom'



import 'bootstrap/dist/css/bootstrap.min.css';

function index() {
  return (
    <div>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Menu />
        
        <div className={`${styles.header} ${styles.banner}`} style={{backgroundImage: `url("img/banner.jpg")`}}>
            <Container className={`${styles.container} ${styles.textCenter}`}>
                <Row>
                    <Col md={12}>
                        <h1><a className="brand" href="/">Gallery</a></h1>
                    </Col>
                </Row>

                <Col md={12}>
                    <h1>Home / Gallery</h1>
                </Col>
            </Container>
        </div>

        <Gallery />

        <Footer />
    </div>
  )
}

export default index