
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import styles from '../styles/Main.module.css'
import Menu from '../components/Menu'
import Header from '../components/Header'
import Gallery from '../components/Gallery'
import Blogs from '../components/Blogs'
import Footer from '../components/Footer'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
  <>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="stylesheet" href="/favicon.ico" /> */}
{/* 
        <link href="template/nature/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="template/nature/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="template/nature/vendor/slick/slick.css" rel="stylesheet" />
        <link href="template/nature/vendor/slick/slick-theme.css" rel="stylesheet" />
		    <link href="template/nature/vendor/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

        <link href="template/nature/css/hover-style.css" rel="stylesheet" />
        <link href="template/nature/css/style.css" rel="stylesheet" /> */}
      </Head>

        <Menu />

        
        <Header />
        
        <Gallery />

        <Blogs />

        <Footer />

        {/* <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/jquery/jquery-migrate.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="vendor/wow/wow.min.js"></script>
        <script src="vendor/slick/slick.min.js"></script>
		<script src="vendor/tempusdominus/js/moment.min.js"></script>
        <script src="vendor/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="vendor/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script> */}
        
    </>
  )
}
