
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Main.module.css'
import Menu from '../../components/Menu'
import Blogs from '../../components/Blogs'
import Footer from '../../components/Footer'
import { Col, Container, Row } from 'react-bootstrap'

import 'bootstrap/dist/css/bootstrap.min.css';


export default function Blog() {
    return (
      <div>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Menu />

        
        <div className={`${styles.header} ${styles.banner}`}>
            <Container className={`${styles.container} ${styles.textCenter}`}>
                <Row>
                    <Col md={12}>
                        <h1><a className="brand" href="/">Nature</a></h1>
                    </Col>
                </Row>

                <Col md={12}>
                    <h1>Home / Blog</h1>
                </Col>
            </Container>
        </div>

        <Blogs />

        <Footer />

      </div>
    )
  }